name: template-wasm-rs
format: 0.1.0
validation: "./workflows/validator.cue"
jobs:
  sampleMethod:
    steps:
      - uri: fs/build
        method: getManifest
        args:
          path: "src/schemas/manifest.example.json"
